import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://bitcoinforthearts.org';
  const now = new Date();

  const routes = [
    '/',
    '/about',
    '/about/reason-for-formation',
    '/about/governance',
    '/about/leadership',
    '/about/leadership/dion-wilson',
    '/about/leadership/avi-burra',
    '/about/leadership/cheryl-mcginnis',
    '/about/leadership/ahmed-klink',
    '/about/leadership/kyle-shirkness',
    '/get-involved',
    '/get-involved/diy-fundraising-guide',
    '/get-involved/volunteer',
    '/get-involved/feedback',
    '/grants',
    '/grants/guidelines',
    '/grants/faq',
    '/programming',
    '/education',
    '/education/open',
    '/artists',
    '/events',
    '/research',
    '/research/state-of-arts-funding-2026',
    '/research/the-arpa-cliff',
    '/stories',
    '/stories/kenneth-burris',
    '/stories/man-like-kweks',
    '/stories/beth-alta-fletcher',
    '/stories/hitomi-matsui',
    '/stories/aksana-zasinets',
    '/stories/a13mw-zap-animations',
    '/stories/matt-finlay',
    '/stories/benjamin-ella',
    '/stories/share-your-story',
    '/art-zap-weekend',
    '/donate',
    '/donate/monthly',
    '/donate/guides/life-insurance',
    '/donate/guides/securities',
    '/donate/guides/ira-qcd',
    '/donate/guides/daf',
    '/donate/guides/estate-planning',
    '/donate/guides/royalties-ip',
    '/contact',
    '/transparency',
    '/transparency/bitcoin-education-initiative-proposal',
    '/transparency/sovereign-artist-residency-proposal',
    '/privacy-policy',
    '/terms',
    '/billing',
    '/sitemap-page',
    '/governance',
    '/artists/why-bitcoin',
    '/education/webinar',
  ];

  return routes.map((url) => ({
    url: `${baseUrl}${url}`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: url === '/' ? 1 : 0.7,
  }));
}

